### ISSUE TITLE
input type, placeholder 설정

### ISSUE THREAD

**Issue by jungmin801** [FRONTENDSCHOOL7/final-14-Deskoration#69]
### 만들고자 하는 기능은 무엇인가?
input type, placeholder 설정

### 해당 기능을 구현하기 위해 할 일은?
1. [x] register form 카테고리 옵션으로 변경
2. [x] register form 구매가격 number type 변경
3. [x] 공통 input 컴포넌트 placeholder 추가
4. [x] placeholder 내용 추가

**Comment by YennieJ** [comment]
- [ ] input에 타입 추가하기
